apiVersion: v1
kind: ConfigMap
metadata:
  name: serenity-assistant-config
  namespace: serenity-assistant
  labels:
    app: serenity-assistant
    component: config
data:
  FLASK_ENV: "production"
  FLASK_APP: "main.py"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  LOG_LEVEL: "INFO"
  WORKERS: "4"
  TIMEOUT: "120"
  KEEP_ALIVE: "2"
  MAX_REQUESTS: "1000"
  MAX_REQUESTS_JITTER: "50"