apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: serenity-assistant
  namespace: serenity-assistant

# Resources to include in the deployment
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgresql.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
  - monitoring.yaml

# Common labels applied to all resources
commonLabels:
  app: serenity-assistant
  version: v1.0.0
  managed-by: kustomize

# Namespace for all resources
namespace: serenity-assistant

# Images to be used
images:
  - name: serenity-assistant
    newTag: latest

# ConfigMap and Secret generators
configMapGenerator:
  - name: serenity-assistant-env-config
    literals:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO

# Patches for different environments
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: serenity-assistant
      namespace: serenity-assistant
    spec:
      template:
        spec:
          containers:
          - name: serenity-assistant
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "1Gi"
                cpu: "1000m"