apiVersion: v1
kind: ServiceMonitor
metadata:
  name: serenity-assistant-monitor
  namespace: serenity-assistant
  labels:
    app: serenity-assistant
    component: monitoring
spec:
  selector:
    matchLabels:
      app: serenity-assistant
      component: webapp
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: serenity-assistant-metrics
  namespace: serenity-assistant
  labels:
    app: serenity-assistant
    component: metrics
spec:
  selector:
    app: serenity-assistant
    component: webapp
  ports:
  - port: 8080
    targetPort: 8080
    name: metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: serenity-assistant
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "alert_rules.yml"
    
    scrape_configs:
      - job_name: 'serenity-assistant'
        static_configs:
          - targets: ['serenity-assistant-service:80']
        metrics_path: /metrics
        scrape_interval: 30s
      
      - job_name: 'postgresql'
        static_configs:
          - targets: ['postgresql-service:5432']
        scrape_interval: 30s
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
  
  alert_rules.yml: |
    groups:
    - name: serenity-assistant-alerts
      rules:
      - alert: HighErrorRate
        expr: rate(flask_http_request_exceptions_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for 5 minutes"
      
      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90%"
      
      - alert: DatabaseConnectionFailure
        expr: up{job="postgresql"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failure"
          description: "PostgreSQL database is not responding"