apiVersion: v1
kind: Secret
metadata:
  name: serenity-assistant-secrets
  namespace: serenity-assistant
  labels:
    app: serenity-assistant
    component: secrets
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # To encode: echo -n "your-secret-value" | base64
  SESSION_SECRET: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="  # change-me-in-production
  DATABASE_URL: "cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXNxbC1zZXJ2aWNlOjU0MzIvbWVudGFsX2hlYWx0aF9kYg=="  # postgresql://user:password@postgresql-service:5432/mental_health_db
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: serenity-assistant
  labels:
    app: serenity-assistant
    component: database
type: Opaque
data:
  # Base64 encoded database credentials
  POSTGRES_USER: "cG9zdGdyZXM="  # postgres
  POSTGRES_PASSWORD: "c2VjdXJlLXBhc3N3b3Jk"  # secure-password
  POSTGRES_DB: "bWVudGFsX2hlYWx0aF9kYg=="  # mental_health_db